CREATE TABLE IF NOT EXISTS todos
(
    id          CHAR(36) NOT NULL PRIMARY KEY,
    description TEXT     NOT NULL,
    due_date    TIMESTAMP NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);